- README.md
- migrations/V1__create_audit_events_table.sql
- migrations/V2__create_billing_and_fraud_events_table.sql
- migrations/V3__create_indexes_for_audit_billing_and_fraud_events_tables.sql
- permissions/create_iam_reader_permissions.sql
- permissions/create_iam_writer_permissions.sql
- permissions/revoke_reader_user_permissions.sql
- permissions/revoke_writer_permissions.sql
This adds the SQL scripts from the [verify-event-recorder-service](https://github.com/alphagov/verify-event-recorder-service).
Going forward all related scripts, schemas and migrations will be held in this repo.
https://trello.com/c/OTm06vLt/67-move-database-sql-scripts-to-new-repo
> Add initial database scripts

- docker-compose.yml
- run-tests.sh
Modify `run-test.sh` to run in `sh` instead of `bash` so it is compatible with the dc-ind Docker image.
Modify docker-compose.yml version to 3.3 so compatible iwth dc-ind Docker image.
Co-authored-by: Alan Carter <alan.carter@digital.cabinet-office.gov.uk>
> j6bt2ppz: Modify pipeline to include steps to build db migrations image for default

- migrations/V1__create_audit_events_table.sql
- migrations/V2__create_billing_and_fraud_events_table.sql
- permissions/change_object_ownership.sql
- permissions/create_event_store_owner_permissions.sql
Add permissions for new role event_system_owner
Change owner of existing objects to event_system_owner
Update existing migration scripts to reflect new owner so that new
environments can be spun up with requirement for additional `postgres` role..
> Nt3YuErJ: Create Flyway User in Terraform

- docker-compose.yml
Currently, the database migrations tests run against the `latest` Postgres Docker image, this currently runs Postgres v11.3. However, the version of a Postgres being run in the AWS environments, and hence the version the migrations will run against, is 10.6.
We need to update the tests so they run against the same version of Postgres.
To avoid any issues that may arise in differences of the SQL commands or Postgres functionality between versions.
Update `docker-compose.yml` to use `10.6` tag instead of `latest` for Postgres image.
> iqUc0u8s: Update database migration tests to use same version of postgres as in AWS

- migrations/V6__copy_event_id_to_billing_events_table.sql
Add new version schema migration to populate data from `audit_events` table.
A second PR will be raised to populate any non-matching rows once they have been identified and analysed.
> Bgg1HWGD: Populate new event_id column in billing_events table - Part 1

- migrations/V6__copy_event_id_to_billing_events_table.sql
Fix invalid SQL causing test failures.
> Bgg1HWGD: Populate new event_id column in billing_events table - SQL Fix

- tools/submit_job.py
The `submit_job.py` script only checked for failure of the batch job
when exiting. This doesn't work for instances where the wait loop times
out. Changing final check to exit non-zero if final status is not
success.
Also, add a check to see if a previous job is still running, and wait for it to terminate, before submitting new job
> BAU: Fix Status Check

- migrations/V6__copy_event_id_to_billing_events_table_before_2016.sql
Update for data prior to 2016 by looking up `event_id` in `audit_events` table. …
> Bgg1HWGD: Populate event_id column in billing_events table (< 2016)

- migrations/V7__copy_event_id_to_billing_events_table_2016.sql
Update for data in year 2016 by looking up `event_id` in `audit_events` table. …
> Bgg1HWGD: Populate event_id column in billing_events table (2016)

- migrations/V8__copy_event_id_to_billing_events_table_2017.sql
Update for data in year 2017 by looking up `event_id` in `audit_events` table. …
> Bgg1HWGD: Populate event_id column in billing_events table (2017)

- migrations/V9__copy_event_id_to_billing_events_table_2018.sql
Update for data in year 2018 by looking up `event_id` in `audit_events` table. …
> Bgg1HWGD: Populate event_id column in billing_events table (2018)

- migrations/V10__copy_event_id_to_billing_events_table_2019.sql
Update for data in year 2019 by looking up `event_id` in `audit_events` table. …
> Bgg1HWGD: Populate event_id column in billing_events table (2019)

- migrations/V11__generate_event_id_for_NULL_values.sql
Add script to populate any unmatched rows that still have a `NULL` value. Simply generate new UUID. There are 26 instances of this in the production database.
> Bgg1HWGD: Populate event_id column in billing_events table (Part 2)

- migrations/V12__create_unique_event_id_index_on_billing_events.sql
- migrations/V13__create_primary_key_on_billing_events.sql
This card will make the column `NOT NULL` and define it as the primary key for the `billing_events` table.
Add migration script to build a unique index (concurrently) for the `event_id` column.
Add migration script to make `event_id` unique index the primary key for the `billing_events` table and alter `event_id` column so that it cannot have `NULL` values.
> yMwmQmiE: Make event_id column the primary key for billing_events table

- migrations/V14__create_foreign_key_constraint_on_billing_status_table.sql
A new table was created with the following:
+ billing status as a text field
+ event_id
Also, a primary key on the `billing_events` table has been added to include the `event_id` field.
We should now define a `FOREIGN KEY`, `REFERENCE`-ing the billing events table.
See:
https://github.com/alphagov/verify-event-system-database-scripts/pull/21
https://github.com/alphagov/verify-event-system-database-scripts/pull/20
https://github.com/alphagov/verify-event-system-database-scripts/pull/11
Add migration script to add foreign key constraint to the `event_id`
column in the `billing_status` table referencing the `event_id` column
from the `billing_events` table.
> THjpCRyp: Add foreign key relation to billing_status table

- permissions/create_billing_status_calculator_permissions.sql
We now have a shiny new table into which we can persist the calculated billing status for billing events.
We now need to write the thing that will populate the table.
This card will give permissions to the thing so it can read the data it requires and write back to the `billing_status` table.
Persisting the billing status will enable more efficient billing reports.
Permissions are required to allow the thing to its job.
Add new script to assign permissions for billng status calculator.
N.B. this script will need to be run manually, in each environment, after the user has been terraformed.
> 2VUuo89R: Database permissions for billing status calculator

- migrations/V20190712122100__create_indexes_on_billing_events_for_reports.sql
We now have the billing status persisted in the database, and it has been verified as correct.
We now need to change the billing report code to use the persisted value instead of calculating the billing status.
It is probably a good idea to have a test that billing status is actually there.
To improve efficiency of billing report.
Add new index on `billing_status` table to be used in new  `LATERAL` join in billing report.
This is a "starter for 10", we may need to add additional indexes.
> EDAtonBP: Update billing report to use persisted billing status - Add Index

- migrations/V20190715165000__create_additional_index_on_audit_events_for_reports.sql
We now have the billing status persisted in the database, and it has been verified as correct. Plus the billing report is now being generated from the persisted data.
We now need to change the verifications by RP report code to use the persisted value instead needing to download and compare the generated billing report for the same period.
It is probably a good idea to have a test that billing status is actually there.
The verifications report, historically, is a fairly long running report. Review queries to ensure it is making best use of indexes and create new as necessary.
Review options on the future of this report
To improve efficiency of billing report.
Add index to `audit_events` table to improve efficiency of report.
> BQOh2juk: Update Verifications Report to use persisted billing status - Add Index

- migrations/V000001__create_audit_events_table.sql
- migrations/V000002__create_billing_and_fraud_events_table.sql
- migrations/V000003__create_indexes_for_audit_billing_and_fraud_events_tables.sql
- migrations/V20190712122100__create_indexes_on_billing_events_for_reports.sql
Ensures all indexes in historical migrations are named for consistency across the databases.
Note that Flyway will reject these migrations due to checksum value changes. This will **need to be repaired manually**.
[Trello](https://trello.com/c/vhQUJhJH/28-index-re-concilation-across-environments)
> Trello vhQUJhJH - Name all indexes

- migrations/R__create_session_id_index_on_audit_events.sql
This index already existed in the production DB. But not in all the other environments. We want to have it in our migrations, both so we know it's there, our tests will be using a production-like schema, we know to remove it if necessary, and it's applied consistently across the other environments. (Plus, code is meant to be self-documenting...)
Note that it has been made repeatable so that if the index needs removing, we only need to add a drop clause in this file.
[Trello](https://trello.com/c/vhQUJhJH/28-index-re-concilation-across-environments)
> Trello vhQUJhJH - Add migration for a pre-existing index

- migrations/V20190724155000__add_transaction_entity_id_to_billing_events.sql
Add new migration to add new column to `billing_events` table.
> NDCBW4d3: Add service name to billing report

- migrations/V20190730105000__copy_transaction_entity_id_to_billing_events_table_before_2016.sql
Add migration to copy data for pre-2016 billing events
> NDCBW4d3: Add service name to billing report - Data Migration pre-2016

- migrations/V20190730105100__copy_transaction_entity_id_to_billing_events_table_2016.sql
Add migration to copy transaction_entity_id to 2016 billing events
> NDCBW4d3: Add service name to billing report - Data Migration 2016

- migrations/V20190730105200__copy_transaction_entity_id_to_billing_events_table_2017.sql
Add migration to copy transaction_entity_id to 2017 billing events
> NDCBW4d3: Add service name to billing report - Data Migration 2017

- migrations/V20190730105300__copy_transaction_entity_id_to_billing_events_table_2018.sql
Add migration to copy transaction_entity_id to 2018 billing events
> NDCBW4d3: Add service name to billing report - Data Migration 2018

- migrations/V20190730105400__copy_transaction_entity_id_to_billing_events_table_2019.sql
Add migration to copy transaction_entity_id to 2019 billing events
> NDCBW4d3: Add service name to billing report - Data Migration 2019

- migrations/V20190805143000_fix_incorrect_event_ids_in_billing_events_table_pre_2018.sql
When we added the `event_id` column to the database last quarter and populated it by matching to data in the `audit_event` table, it seems that a small proportion of the rows matched to an incorrect event.
We need to identify these rows and update them with the correct `event_id`, ensuring that the corresponding `billing_status` record is also updated.
We need to ensure the correct data integrity so that reports for historical periods will run correctly.
Add migration script to identify incorrect assigned `event_id`s and correct them (and the `transaction_entity_id`) for data before 2018-01-01.
> Q3k5BlPI: Fix incorrect event_ids in billing_status table - Pre-2018

- migrations/V20190815122000__add_event_id_to_fraud_table.sql
As a developer, I want to be able to join between data in the `billing.fraud_events` table and the more detailed information in the `audit_events` table.
* For consistency with billing events, the primary key should be event ID
* Add the `transaction_entity_id` to fraud_events also
Add `event_id` and `transaction_entity_id` columns to `billing.fraud_events`.
> LbFKGVYc: Fixes to database schema for existing fraud data

- permissions/create_iam_reader_permissions.sql
There is a new table in the DB. The reader / writer should probably be given access to them.
> BAU - Add permissions to status table for IAM roles

- migrations/V20190815160000__populate_event_id_and_transaction_entity_id_in_fraud_events_table.sql
As a developer, I want to be able to join between data in the `billing.fraud_events` table and the more detailed information in the `audit_events` table.
* For consistency with billing events, the primary key should be event ID
* Add the `transaction_entity_id` to fraud_events also
https://github.com/alphagov/verify-event-system-database-scripts/pull/41
Add update script to populate `event_id` and `transaction_entity_id`.
> LbFKGVYc: Fixes to database schema for existing fraud data - Historical Data Update

- migrations/V20190815160000__populate_event_id_and_transaction_entity_id_in_fraud_events_table.sql
Correct mis-typed alias in `UPDATE` query causing syntax error.
> BAU: Fix typo in UPDATE query causing migration to fail

- migrations/V20190815161000__make_event_id_primary_key_index_on_fraud_events.sql
As a developer, I want to be able to join between data in the `billing.fraud_events` table and the more detailed information in the `audit_events` table.
* For consistency with billing events, the primary key should be event ID
* Add the `transaction_entity_id` to fraud_events also
https://github.com/alphagov/verify-event-system-database-scripts/pull/41
https://github.com/alphagov/verify-event-system-database-scripts/pull/42
Make event_id `NOT NULL`
Create PRIMARY KEY index on `fraud_events` table.
> LbFKGVYc: Fixes to database schema for existing fraud data - Make Primary Key

- migrations/V20191009113000__drop_unique_index_and_event_id_column_from_idp_fraud_events.sql
Further decisions have been made following the loading of real data, we have decided to alter our schema to reflect to remove the matching `event_id` column and to also remove the uniqueness constraint on the around the `idp_event_id` column.
Drop `index idp_data.idp_fraud_events_idp_entity_id_idp_event_id_idx` as
uniqueness cannot be guaranteed.
Remove `event_id` column matching should be perform by user.
> YYdbmOJJ: Drop columns and index

- migrations/V20200428161000__add_preferred_loa_column_to_billing_events_table copy.sql
- migrations/V20200428163000__alter_required_field_to_be_nullable_on_the_billing_events_table.sql
This PR is one part of several across Verify to be able to support billing for new special case `LOA2,LOA1/exact` requests. It contains 2 database migrations.
Going forwards:
* The preferred LOA will be used as a part of the billing calculation (but it is not going to be backfilled, so the column should remain nullable).
* The required LOA is no longer recorded (and in fact was never needed).
The two migrations are:
* Adds a new (nullable) `preferred_level_of_assurance` column to the `billing_events` table.
* Sets the `required_level_of_assurance` column in the `billing_events` table to be nullable.
The `required_level_of_assurance` column will be removed in a future PR after all the billing alterations have been successful.
The full set of changes being made is laid out in:
* [ADR 36 …
> ps34 Add new preferred LOA billing column to billing_events

- migrations/V20200602103000__drop_required_level_of_assurance_column_from_billing_events.sql
- The required_level_of_assurance was never used for billing and is no longer being populated. Therefore we can
drop this column completely.
Co-authored-by: Lewis Westbury <lewis.wetbury@digital.cabinet-office.gov.uk>
> Drop required_level_of_assurance column

- migrations/V20200907155900__create_audit_session_requests_table.sql
- migrations/V20200909115900__create_min_audit_event_date_function.sql
- migrations/V20200909173300__create_max_audit_event_date_function.sql
- migrations/V20200909173500__create_audit_session_requests_function.sql
See: https://govukverify.atlassian.net/browse/HUB-717
This PR contains the creation script for the new table (**audit_event_session_requests**) and core functions that would be used to import request and session ids from the audit_events table to the new table.
1. **fn_inserts_audit_event_session_requests** can be called to start the import, it uses 2 helper functions to find the earliest date i.e. **min_audit_date()** and the latest date i.e. **max_audit_date()** functions. However, since the audit_events table is very large the intention is the run separate migration script files for shorter ranges i.e. a script file can be created that runs the following command see https://github.com/alphagov/verify-event-system-database-scripts/pull/50
```
DO $$ BEGIN
PERFORM …
```
> Hub-717: extract requestid from audits details import function

- migrations/V20200915093000__alter_audit_session_requests_owner.sql
This commit changes ownership on the audit session requests object i.e
- audit_event_session_request table
- min_audit_date function
- max_audit_date function
from dbmigrator to event_system_owner
> HUB-717: alter ownership on session request object

- migrations/V20200915142000__migrate_request_ids_to_audit_event_session_requests_table_for_20200409-10.sql
A function has been created to copy request_id and session_id data from
the main audit_events table to the new audit_event_session_requests
table.
It's been realised that there is a _lot_ of data that will be copied.
This initial migration is to copy data for a conservative two days of
the initial date period we're interested in. We will observe how this
migration runs and adjust future migrations as appropriate.
This migration file has been tested against the local set up described in 
the README.
> HUB-717: Add migration for initial two days of request ids

- migrations/V20200915162000__migrate_request_ids_to_audit_event_session_requests_table_for_20200410-17.sql
This is being done in small increments to prevent any issues with
locking the DB. The previous migration operated on two days worth of
data and the DB instance had no issues. CPU usage rose to 5% and the
time for the migrations to happen was not abnormal. The event system db
dashboard showed no worrying stats.
This migration will operated on a week of data. After this we could step
up to a month.
> HUB-717: Add migration for request_ids for April 10-17

- migrations/V20200915172000__migrate_request_ids_to_audit_event_session_requests_table_for_20200417-0517.sql
This is the third migration of this kind, gradually increasing in size.
Previously we ran two days and a week without any DB issues.
> HUB-717: Add migration for request_ids for April 17 to May 17

- migrations/V20200916091500__migrate_request_ids_to_audit_event_session_requests_table_for_20200517-0917.sql
The previous migration was for one month and the DB handled it like a
champ.
This migration is for four months and will mean that all data since
since the 9th April up until the point this migration is run will be
migrated.
After this I will proceed in 6 month or one year increments from the
first row in the audit_events table up until 9th April.
> HUB-717: Extract request_id for May 17 to Sept 17

- migrations/V20200916112500__migrate_request_ids_to_audit_event_session_requests_table_for_20140905-20150505.sql
The previous migration was for a four month period and ran without
issues. This increases the time period to eight months.
As we have now migrated the most recent data this will operate on the
earliest time_stamp and later. The default argument to the function,
`beginning` is omitted here so the default is used - the earliest
time_stamp in the table. Having inspected the DB this is 5 September
2014.
> HUB-717: Add migration for request_id for 20140905 to 20150505

- migrations/V20200916135500__migrate_request_ids_to_audit_event_session_requests_table_for_20150505-20170101.sql
The last migration was for 8 months and ran without issue.
This migration is for a approximately 19 month period, so a little more
than double. It makes the date ranges more sensible though.
> HUB-717: Add migration for request_id for 20150505 to 20170101

- migrations/V20200916154500__migrate_request_ids_to_audit_event_session_requests_table_for_2017.sql
The previous migration of 18 months was successful but took 35 minutes
and caused the script running it to falsely report a failure. As such
I've reduced the time period to 12 months.
> HUB-717: Migrate request_ids for 2017

- migrations/V20200917120000__migrate_request_ids_to_audit_event_session_requests_table_for_20190101-0701.sql
We've found that there are more events the later the date range and the
migrations were taking longer to run. I'm going to migrate 2019 in two
parts to address this. This is the first half of the year.
> HUB-717: Add migration for request_id for 20190101-0701

- migrations/V20200917120300__migrate_request_ids_to_audit_event_session_requests_table_for_20190701-20200101.sql
This is second half of 2019. 2019 has more events than 2018 so the
migration is being done in two parts rather than the whole year in one
shot.
> HUB-717: Add request_id migration for 20190701 to 20200101

- migrations/V20200916155000__migrate_request_ids_to_audit_event_session_requests_table_for_20200101-to-20200409.sql
The data from 20200409 onwards has already been migrated.
> HUB-717: Add migration for request_id for 20200101 to 20200409

- migrations/V202009251643260__migrate_request_ids_to_audit_event_session_requests_table_for_20200409-to-20200925.sql
- migrations/V202009251644480__create_index_on_session_id_in_audit_event_session_requests_table.sql
- migrations/V202009251645450__create_index_on_request_id_in_audit_event_session_requests_table.sql
* Add an additional migration for the `audit_events_session_requests` table from 2020-04-01 to 2020-09-25.
* Add indices on `request_id` and `session_id` columns the `audit_events_session_requests` table.
For more info on the function, see [migration V20200909173500](https://github.com/alphagov/verify-event-system-database-scripts/blob/master/migrations/V20200909173500__create_audit_session_requests_function.sql), where it was created.
> BAU add migration to link session_id, request_id for 2020-04 to 2020-09-25

- migrations/V202009291300110__recreate_audit_session_requests_table.sql
- migrations/V202009291430110__recreate_audit_session_requests_function.sql
- migrations/V202009291444110__migrate_request_ids_to_audit_event_session_requests_table_for_20200409_to_present.sql
- migrations/V202009291646450__create_index_on_request_id_in_audit_event_session_requests_table_again.sql
- migrations/V202009291646480__create_index_on_session_id_in_audit_event_session_requests_table_again.sql
* Recreates the function for migrating data to `audit_event_session_requests`
* Recreates the `audit_event_session_requests` table with a column for `details` as jsonb
* Disallows accidental overwrite of useful values for `request_id` by empty strings
* Fetches only data from relevant dates for HUB-719 query
> HUB-719 recreate table and function
